### ISSUE TITLE
Password Can't Contain Uppercase Letter

### ISSUE THREAD

**Issue by a178235** [froggleston/freqtrade-frogtrade9000#3]
pass works but Pass raises Exception("Cannot parse server option. Please use [name]user:pass@servername:port").

**Comment by a178235** [comment]
That fixed the password issue. Now I'm getting the following error. I'm using Windows 10 WSL Ubuntu 21.04. Perhaps it has something to do with WSL?

Traceback (most recent call last):
  File "frogtrade9000.py", line 459, in <module>
    main()
  File "frogtrade9000.py", line 432, in main
    keyboard.on_press(key_press)
  File "/usr/local/lib/python3.9/dist-packages/keyboard/__init__.py", line 474, in on_press
    return hook(lambda e: e.event_type == KEY_UP or callback(e), suppress=suppress)
  File "/usr/local/lib/python3.9/dist-packages/keyboard/__init__.py", line 461, in hook
    append(callback)
  File "/usr/local/lib/python3.9/dist-packages/keyboard/_generic.py", line 67, in add_handler
    self.start_if_necessary()
  File "/usr/local/lib/python3.9/dist-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/usr/local/lib/python3.9/dist-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/usr/local/lib/python3.9/dist-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/usr/local/lib/python3.9/dist-packages/keyboard/_nixkeyboard.py", line 110, in build_device
    device = aggregate_devices('kbd')
  File "/usr/local/lib/python3.9/dist-packages/keyboard/_nixcommon.py", line 168, in aggregate_devices
    assert fake_device
AssertionError
You got frogged:

**Comment by froggleston** [comment]
Hm yeah it'll be some keyboard issue. Try running it without sudo/root? Does it start then?
________________________________

**Comment by froggleston** [comment]
I'll close this issue as the original problem is resolved. Please open another issue if you're still having problems. The OS-specific keyboard issues are known and not easily fixable.
